### ISSUE TITLE
WorldObject Documentation

### ISSUE THREAD

**Issue by vkuehn** [ADefWebserver/AutomaticKingdom#7]
Impresseive Demo. Can you explain how/where the WordObject is defined and how own Objects can be added ?

So No an Issue, could be marked as documentation

**Comment by ADefWebserver** [comment]
A `WorldObject` is a [Babylon Mesh](https://doc.babylonjs.com/typedoc/classes/babylon.mesh). Currently it is defined in an associated .razor file located in the `BabylonControls` folder. The eventual plan is to make it more generic and extensible.

**Comment by vkuehn** [comment]
that would be great. Thanks
